# Generated by Django 3.1.7 on 2021-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettable',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
