# Generated by Django 3.1.7 on 2021-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyp_app', '0002_datasettable_is_trained'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
                ('detected', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
